In [2]:
import tensorflow_datasets as tfds

In [3]:
train_ds = tfds.load('tf_housing', split='train')

In [9]:
a_sample = train_ds.take(1)
for an_ex in a_sample:
    print(an_ex)

{'date_end': <tf.Tensor: shape=(), dtype=float32, numpy=18079.0>, 'land/depth': <tf.Tensor: shape=(), dtype=float32, numpy=200.9>, 'land/front': <tf.Tensor: shape=(), dtype=float32, numpy=93.41>, 'map/lat': <tf.Tensor: shape=(), dtype=float32, numpy=44.55023>, 'map/lon': <tf.Tensor: shape=(), dtype=float32, numpy=-79.41331>, 'metadata': {'ml_num': <tf.Tensor: shape=(), dtype=string, numpy=b'206287'>}, 'sold_price': <tf.Tensor: shape=(), dtype=float32, numpy=870000.0>}


In [10]:
batches = train_ds.batch(batch_size = 10)

In [11]:
for a_batch in batches.take(1):
    print(a_batch)

{'date_end': <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([18079., 18045., 18225., 18186., 18023., 18074., 17926., 18135.,
       18071., 17973.], dtype=float32)>, 'land/depth': <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([200.9 ,   1.  , 109.  , 111.77, 116.  , 156.  , 130.27, 115.  ,
        59.  ,   1.  ], dtype=float32)>, 'land/front': <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 93.41,   1.  ,  75.  ,  49.21, 118.01,  17.67,  72.83,  25.  ,
       129.  ,   1.  ], dtype=float32)>, 'map/lat': <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([44.55023 , 43.50414 , 44.11433 , 43.89475 , 43.6678  , 43.68098 ,
       43.51707 , 44.205917, 43.79596 , 43.641026], dtype=float32)>, 'map/lon': <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-79.41331, -79.87949, -79.11518, -79.24115, -79.54058, -79.28829,
       -79.61995, -77.39651, -79.28582, -79.55904], dtype=float32)>, 'metadata': {'ml_num': <tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'2062

In [17]:
dir(train_ds)

['_GeneratorState',
 '__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_add_variable_with_custom_getter',
 '_apply_options',
 '_as_serialized_graph',
 '_buffer_size',
 '_checkpoint_dependencies',
 '_consumers',
 '_deferred_dependencies',
 '_flat_shapes',
 '_flat_structure',
 '_flat_types',
 '_functions',
 '_gather_saveables_for_checkpoint',
 '_graph',
 '_graph_attr',
 '_handle_deferred_dependencies',
 '_has_captured_ref',
 '_input_dataset',
 '_inputs',
 '_list_extra_dependencies_for_serialization',
 '_list_functions_for_serialization',
 '_lookup_dependency',
 '_maybe_initialize_trackable',
 '_name_based_attribute_restore

In [21]:
train_ds.element_spec.keys()

dict_keys(['date_end', 'land/depth', 'land/front', 'map/lat', 'map/lon', 'metadata', 'sold_price'])

In [22]:
type(train_ds)

tensorflow.python.data.ops.dataset_ops.PrefetchDataset